---
title: "nbaplayers"
author: "Ian Thorpe"
date: "4/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(car)
```


```{r}
player_data <- read.csv('final_df.csv') %>%
  na.omit()
```

```{r}
center_data <- player_data %>%
  filter(POS == 'C') %>%
  select(c(raptor_offense, raptor_defense))

center_means <- colMeans(center_data)
center_cov <- cov(center_data)

n = dim(center_data)[1]
p = dim(center_data)[2]
alpha = 0.05



t_crit <- (n-1) * p / (n-p) * qf(p = 1-alpha, df1 = p, df2 = n-p)
plot(center_data[ , 1], center_data[ , 2], xlab = "Raptor Offense", ylab = "Raptor Defense")
points(center_means[1], center_means[2], pch = 4, cex = 1.3, col = "gray30")
points(ellipse(center = center_means, shape = center_cov, radius = sqrt(t_crit/n), draw = FALSE), type = 'l')
points(8.590943, 5.868475, col = 'blue')
text(8.5, 7, 'Jokic')
points(3.9, 3.7, col = 'red')
text(3.9, 5, 'Embiid')
title('Raptor Ratings for NBA Centers')
```

```{r}
player_data %>%
  select(c(raptor_offense, raptor_defense)) -> entire_nba

nba_means <- colMeans(entire_nba)
nba_cov <- cov(entire_nba)

n = dim(entire_nba)[1]
p = dim(entire_nba)[2]
alpha = 0.05



t_crit <- (n-1) * p / (n-p) * qf(p = 1-alpha, df1 = p, df2 = n-p)
plot(entire_nba[ , 1], entire_nba[ , 2], xlab = "Raptor Offense", ylab = "Raptor Defense")
points(nba_means[1], nba_means[2], pch = 4, cex = 1.3, col = "gray30")
points(ellipse(center = nba_means, shape = nba_cov, radius = sqrt(t_crit/n), draw = FALSE), type = 'l', col = 'pink')
points(8.590943, 5.868475, col = 'blue')
text(8.5, 7, 'Jokic')
points(3.9, 3.7, col = 'red')
text(3.9, 5, 'Embiid')
points(4.7, -0.9, col = 'lightblue')
text(4.7, 0, 'Morant')
points(6, 0.9, col = 'blue')
text(6, 2, 'Curry')
title('Raptor Ratings for NBA Players')
```

```{r}
player_data %>%
  filter(TM == 'DEN') %>%
  select(c(raptor_offense, raptor_defense)) -> nuggets_data
 
player_data %>%
  filter(TM == 'PHI') %>%
  select(c(raptor_offense, raptor_defense)) -> sixers_data 

plot(sixers_data[, 1], sixers_data[, 2], xlab = 'Raptor Offense', ylab = 'Raptor Defense', xlim = c(-7, 5))
title('Philadelphia 76ers')
points(3.9, 3.7, col = 'red')


```

```{r}
plot(nuggets_data[, 1], nuggets_data[, 2], xlab = 'Raptor Offense', ylab = 'Raptor Defense')
title('Denver Nuggets')
points(8.590943, 5.868475, col = 'blue')
```

```{r}
embiid <- c(3.9, 3.7)

sixers_data_update <- sixers_data[-(8:10), ]


colMeans(nuggets_data[-4, ])
colMeans(nuggets_data)



colMeans(sixers_data_update[-7, ])
colMeans(sixers_data_update)

```

```{r}
embiid <- c(3.9, 3.7)
jokic <- c(8.590943, 5.868475)

nba_inv <- solve(nba_cov)

sqrt(t(jokic - nba_means) %*% nba_inv %*% (jokic - nba_means))
sqrt(t(embiid - nba_means) %*% nba_inv %*% (embiid - nba_means))
```

